version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data:/vol/web
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/web
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
